apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
    spec:
      containers:
      - image: 9674007/udagram-frontend
        name: udagram-frontend
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8100
      restartPolicy: Always